name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set version
      id: version
      run: echo "VERSION=$(date +%s)" >> $GITHUB_ENV
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag code-buddy:${{ env.VERSION }}
    - name: Log in to GitHub Container Registry
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

    - name: Push Docker image
      run: |
        IMAGE_ID=ghcr.io/${{ github.repository }}
        IMAGE_ID=$(echo $IMAGE_ID | tr '[:upper:]' '[:lower:]')
        docker tag code-buddy:${{ env.VERSION }} $IMAGE_ID:${{ env.VERSION }}
        docker push $IMAGE_ID:${{ env.VERSION }}
    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

    - name: Push Docker image
      run: |
        DOCKERHUB_IMAGE=$(echo ${{ secrets.DOCKERHUB_USERNAME }}/code-buddy | tr '[:upper:]' '[:lower:]')
        docker tag code-buddy:${{ env.VERSION }} $DOCKERHUB_IMAGE:${{ env.VERSION }}
        docker push $DOCKERHUB_IMAGE:${{ env.VERSION }}
